// <auto-generated />
using System;
using BackendPolifood.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendPolifood.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendPolifood.Models.Products.Product", b =>
            {
                b.Property<Guid>("productId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("category")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("imageUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("isActive")
                    .HasColumnType("int");

                b.Property<bool>("isAvailable")
                    .HasColumnType("bit");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("price")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("storeId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("productId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("BackendPolifood.Models.Orders.Order", b =>
            {
                b.Property<Guid>("orderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("createdAt")
                    .HasColumnType("datetime2");

                b.Property<int>("etaMinutes")
                    .HasColumnType("int");

                b.Property<int>("isActive")
                    .HasColumnType("int");

                b.Property<int>("status")
                    .HasColumnType("int");

                b.Property<Guid>("storeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("studentId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("total")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("orderId");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("BackendPolifood.Models.Orders.OrderItem", b =>
            {
                b.Property<Guid>("orderItemId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("orderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("price")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("productId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("productName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("quantity")
                    .HasColumnType("int");

                b.HasKey("orderItemId");

                b.HasIndex("orderId");

                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("BackendPolifood.Models.Store", b =>
            {
                b.Property<Guid>("storeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("available")
                    .HasColumnType("int");

                b.PrimitiveCollection<string>("categories")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("storeId");

                b.ToTable("Stores");
            });

            modelBuilder.Entity("BackendPolifood.Models.Users.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("nvarchar(13)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<int>("active")
                    .HasColumnType("int");

                b.Property<string>("nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("userRole")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers", (string)null);

                b.HasDiscriminator<string>("Discriminator").HasValue("User");

                b.UseTphMappingStrategy();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

            modelBuilder.Entity("BackendPolifood.Models.Users.Admin", b =>
            {
                b.HasBaseType("BackendPolifood.Models.Users.User");

                b.HasDiscriminator().HasValue("Admin");
            });

            modelBuilder.Entity("BackendPolifood.Models.Users.Estudiante", b =>
            {
                b.HasBaseType("BackendPolifood.Models.Users.User");

                b.HasDiscriminator().HasValue("Estudiante");
            });

            modelBuilder.Entity("BackendPolifood.Models.Users.Vendor", b =>
            {
                b.HasBaseType("BackendPolifood.Models.Users.User");

                b.Property<Guid>("storeId")
                    .HasColumnType("uniqueidentifier");

                b.HasIndex("storeId");

                b.HasDiscriminator().HasValue("Vendor");
            });

            modelBuilder.Entity("BackendPolifood.Models.Orders.OrderItem", b =>
            {
                b.HasOne("BackendPolifood.Models.Orders.Order", "order")
                    .WithMany("items")
                    .HasForeignKey("orderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("order");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("BackendPolifood.Models.Users.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("BackendPolifood.Models.Users.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BackendPolifood.Models.Users.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("BackendPolifood.Models.Users.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("BackendPolifood.Models.Users.Vendor", b =>
            {
                b.HasOne("BackendPolifood.Models.Store", "Store")
                    .WithMany()
                    .HasForeignKey("storeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Store");
            });

            modelBuilder.Entity("BackendPolifood.Models.Orders.Order", b =>
            {
                b.Navigation("items");
            });
#pragma warning restore 612, 618
        }
    }
}
